export class Business {
    constructor( 
        public id: any,
        public userId?: string,
        public rowid?: string,
        public directory?: string,
        public gravatar?: any,
        public officeName?: string,
        public mobile?: string,
        public otherNames?: string,
        public email?: string,    
        public gender?: string,
        public maritalStatus?: string,
        public homeTown?: string,      
        public position?: string,
        public latitude?: any,
        public longitude?: any,
        public group?: string,
        public findMeId?: any,
        public location?: any,
        public websiteUrl?: string,
        public fileUpload?: any,
        public landSize?: any,
        public otherInfo?: any,
        public timeDate?: any,
        public dob?:any) {}
}